export interface CountryOption {
  code: string;           // Country Code (ISO 2)
  dialCode: string;       // Dial Code (+92)
  name: string;           // Country Name
  flag: string;           // Emoji Flag
  currency: string;       // ISO Currency Code (PKR, USD, AED, EUR, etc.)
  currencySymbol: string; // Symbol / Display ($ , PKR, £, €, AED, etc.)
  cities: string[];       // Major Cities
}

// Comprehensive World Countries & Major Cities with Dynamic Currencies (Israel Excluded)
export const WORLD_COUNTRIES: CountryOption[] = [
  {
    code: 'PK',
    dialCode: '+92',
    name: 'Pakistan',
    flag: '🇵🇰',
    currency: 'PKR',
    currencySymbol: 'PKR',
    cities: [
      'Karachi',
      'Lahore',
      'Islamabad',
      'Rawalpindi',
      'Faisalabad',
      'Multan',
      'Peshawar',
      'Quetta',
      'Sialkot',
      'Gujranwala',
      'Hyderabad',
      'Abbottabad',
      'Sukkur',
      'Larkana',
      'Bahawalpur',
      'Rahim Yar Khan',
      'Mirpur (AJK)',
      'Muzaffarabad',
    ],
  },
  {
    code: 'US',
    dialCode: '+1',
    name: 'United States',
    flag: '🇺🇸',
    currency: 'USD',
    currencySymbol: '$',
    cities: [
      'New York, NY',
      'San Francisco, CA',
      'Los Angeles, CA',
      'Chicago, IL',
      'Austin, TX',
      'Seattle, WA',
      'Boston, MA',
      'Miami, FL',
      'Atlanta, GA',
      'Denver, CO',
      'Dallas, TX',
      'Washington, D.C.',
      'San Jose, CA',
    ],
  },
  {
    code: 'GB',
    dialCode: '+44',
    name: 'United Kingdom',
    flag: '🇬🇧',
    currency: 'GBP',
    currencySymbol: '£',
    cities: [
      'London',
      'Manchester',
      'Birmingham',
      'Edinburgh',
      'Glasgow',
      'Leeds',
      'Bristol',
      'Cambridge',
      'Oxford',
      'Liverpool',
      'Belfast',
      'Sheffield',
    ],
  },
  {
    code: 'AE',
    dialCode: '+971',
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    currency: 'AED',
    currencySymbol: 'AED',
    cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Al Ain', 'Fujairah'],
  },
  {
    code: 'SA',
    dialCode: '+966',
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    currency: 'SAR',
    currencySymbol: 'SAR',
    cities: ['Riyadh', 'Jeddah', 'Dammam', 'Mecca', 'Medina', 'Khobar', 'Tabuk', 'Abha', 'Jubail'],
  },
  {
    code: 'CA',
    dialCode: '+1',
    name: 'Canada',
    flag: '🇨🇦',
    currency: 'CAD',
    currencySymbol: 'CA$',
    cities: ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton', 'Quebec City', 'Winnipeg'],
  },
  {
    code: 'DE',
    dialCode: '+49',
    name: 'Germany',
    flag: '🇩🇪',
    currency: 'EUR',
    currencySymbol: '€',
    cities: ['Berlin', 'Munich', 'Frankfurt', 'Hamburg', 'Cologne', 'Stuttgart', 'Düsseldorf', 'Dresden'],
  },
  {
    code: 'AU',
    dialCode: '+61',
    name: 'Australia',
    flag: '🇦🇺',
    currency: 'AUD',
    currencySymbol: 'A$',
    cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 'Gold Coast'],
  },
  {
    code: 'IN',
    dialCode: '+91',
    name: 'India',
    flag: '🇮🇳',
    currency: 'INR',
    currencySymbol: '₹',
    cities: ['Mumbai', 'Bengaluru', 'Delhi', 'Hyderabad', 'Pune', 'Chennai', 'Noida', 'Gurgaon', 'Kolkata', 'Ahmedabad'],
  },
  {
    code: 'TR',
    dialCode: '+90',
    name: 'Turkey',
    flag: '🇹🇷',
    currency: 'TRY',
    currencySymbol: '₺',
    cities: ['Istanbul', 'Ankara', 'Izmir', 'Antalya', 'Bursa', 'Adana', 'Gaziantep'],
  },
  {
    code: 'QA',
    dialCode: '+974',
    name: 'Qatar',
    flag: '🇶🇦',
    currency: 'QAR',
    currencySymbol: 'QAR',
    cities: ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Dukhan'],
  },
  {
    code: 'KW',
    dialCode: '+965',
    name: 'Kuwait',
    flag: '🇰🇼',
    currency: 'KWD',
    currencySymbol: 'KWD',
    cities: ['Kuwait City', 'Hawalli', 'Salmiya', 'Ahmadi', 'Farwaniya'],
  },
  {
    code: 'OM',
    dialCode: '+968',
    name: 'Oman',
    flag: '🇴🇲',
    currency: 'OMR',
    currencySymbol: 'OMR',
    cities: ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur'],
  },
  {
    code: 'BH',
    dialCode: '+973',
    name: 'Bahrain',
    flag: '🇧🇭',
    currency: 'BHD',
    currencySymbol: 'BHD',
    cities: ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'],
  },
  {
    code: 'MY',
    dialCode: '+60',
    name: 'Malaysia',
    flag: '🇲🇾',
    currency: 'MYR',
    currencySymbol: 'RM',
    cities: ['Kuala Lumpur', 'Penang', 'Johor Bahru', 'Shah Alam', 'Petaling Jaya', 'Malacca'],
  },
  {
    code: 'SG',
    dialCode: '+65',
    name: 'Singapore',
    flag: '🇸🇬',
    currency: 'SGD',
    currencySymbol: 'S$',
    cities: ['Singapore City', 'Jurong East', 'Woodlands', 'Tampines'],
  },
  {
    code: 'ID',
    dialCode: '+62',
    name: 'Indonesia',
    flag: '🇮🇩',
    currency: 'IDR',
    currencySymbol: 'Rp',
    cities: ['Jakarta', 'Bali', 'Surabaya', 'Bandung', 'Medan', 'Yogyakarta'],
  },
  {
    code: 'CN',
    dialCode: '+86',
    name: 'China',
    flag: '🇨🇳',
    currency: 'CNY',
    currencySymbol: '¥',
    cities: ['Beijing', 'Shanghai', 'Shenzhen', 'Guangzhou', 'Hangzhou', 'Chengdu'],
  },
  {
    code: 'JP',
    dialCode: '+81',
    name: 'Japan',
    flag: '🇯🇵',
    currency: 'JPY',
    currencySymbol: '¥',
    cities: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Fukuoka', 'Sapporo'],
  },
  {
    code: 'KR',
    dialCode: '+82',
    name: 'South Korea',
    flag: '🇰🇷',
    currency: 'KRW',
    currencySymbol: '₩',
    cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon'],
  },
  {
    code: 'FR',
    dialCode: '+33',
    name: 'France',
    flag: '🇫🇷',
    currency: 'EUR',
    currencySymbol: '€',
    cities: ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Bordeaux', 'Lille'],
  },
  {
    code: 'ES',
    dialCode: '+34',
    name: 'Spain',
    flag: '🇪🇸',
    currency: 'EUR',
    currencySymbol: '€',
    cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Bilbao', 'Malaga'],
  },
  {
    code: 'IT',
    dialCode: '+39',
    name: 'Italy',
    flag: '🇮🇹',
    currency: 'EUR',
    currencySymbol: '€',
    cities: ['Rome', 'Milan', 'Florence', 'Venice', 'Naples', 'Turin', 'Bologna'],
  },
  {
    code: 'NL',
    dialCode: '+31',
    name: 'Netherlands',
    flag: '🇳🇱',
    currency: 'EUR',
    currencySymbol: '€',
    cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven'],
  },
  {
    code: 'SE',
    dialCode: '+46',
    name: 'Sweden',
    flag: '🇸🇪',
    currency: 'SEK',
    currencySymbol: 'kr',
    cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala'],
  },
  {
    code: 'NO',
    dialCode: '+47',
    name: 'Norway',
    flag: '🇳🇴',
    currency: 'NOK',
    currencySymbol: 'kr',
    cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
  },
  {
    code: 'DK',
    dialCode: '+45',
    name: 'Denmark',
    flag: '🇩🇰',
    currency: 'DKK',
    currencySymbol: 'kr',
    cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'],
  },
  {
    code: 'FI',
    dialCode: '+358',
    name: 'Finland',
    flag: '🇫🇮',
    currency: 'EUR',
    currencySymbol: '€',
    cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu'],
  },
  {
    code: 'CH',
    dialCode: '+41',
    name: 'Switzerland',
    flag: '🇨🇭',
    currency: 'CHF',
    currencySymbol: 'CHF',
    cities: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne'],
  },
  {
    code: 'AT',
    dialCode: '+43',
    name: 'Austria',
    flag: '🇦🇹',
    currency: 'EUR',
    currencySymbol: '€',
    cities: ['Vienna', 'Salzburg', 'Graz', 'Innsbruck'],
  },
  {
    code: 'BE',
    dialCode: '+32',
    name: 'Belgium',
    flag: '🇧🇪',
    currency: 'EUR',
    currencySymbol: '€',
    cities: ['Brussels', 'Antwerp', 'Ghent', 'Bruges'],
  },
  {
    code: 'IE',
    dialCode: '+353',
    name: 'Ireland',
    flag: '🇮🇪',
    currency: 'EUR',
    currencySymbol: '€',
    cities: ['Dublin', 'Cork', 'Galway', 'Limerick'],
  },
  {
    code: 'NZ',
    dialCode: '+64',
    name: 'New Zealand',
    flag: '🇳🇿',
    currency: 'NZD',
    currencySymbol: 'NZ$',
    cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
  },
  {
    code: 'ZA',
    dialCode: '+27',
    name: 'South Africa',
    flag: '🇿🇦',
    currency: 'ZAR',
    currencySymbol: 'R',
    cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria'],
  },
  {
    code: 'EG',
    dialCode: '+20',
    name: 'Egypt',
    flag: '🇪🇬',
    currency: 'EGP',
    currencySymbol: 'EGP',
    cities: ['Cairo', 'Alexandria', 'Giza', 'Sharm El Sheikh', 'Hurghada'],
  },
  {
    code: 'NG',
    dialCode: '+234',
    name: 'Nigeria',
    flag: '🇳🇬',
    currency: 'NGN',
    currencySymbol: '₦',
    cities: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt'],
  },
  {
    code: 'KE',
    dialCode: '+254',
    name: 'Kenya',
    flag: '🇰🇪',
    currency: 'KES',
    currencySymbol: 'KSh',
    cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
  },
  {
    code: 'BD',
    dialCode: '+880',
    name: 'Bangladesh',
    flag: '🇧🇩',
    currency: 'BDT',
    currencySymbol: '৳',
    cities: ['Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna'],
  },
  {
    code: 'LK',
    dialCode: '+94',
    name: 'Sri Lanka',
    flag: '🇱🇰',
    currency: 'LKR',
    currencySymbol: 'Rs',
    cities: ['Colombo', 'Kandy', 'Galle', 'Jaffna'],
  },
  {
    code: 'NP',
    dialCode: '+977',
    name: 'Nepal',
    flag: '🇳🇵',
    currency: 'NPR',
    currencySymbol: 'Rs',
    cities: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar'],
  },
  {
    code: 'BR',
    dialCode: '+55',
    name: 'Brazil',
    flag: '🇧🇷',
    currency: 'BRL',
    currencySymbol: 'R$',
    cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza'],
  },
  {
    code: 'MX',
    dialCode: '+52',
    name: 'Mexico',
    flag: '🇲🇽',
    currency: 'MXN',
    currencySymbol: 'Mex$',
    cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Cancún', 'Tijuana'],
  },
  {
    code: 'AR',
    dialCode: '+54',
    name: 'Argentina',
    flag: '🇦🇷',
    currency: 'ARS',
    currencySymbol: 'ARS$',
    cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'],
  },
  {
    code: 'CL',
    dialCode: '+56',
    name: 'Chile',
    flag: '🇨🇱',
    currency: 'CLP',
    currencySymbol: 'CLP$',
    cities: ['Santiago', 'Valparaíso', 'Concepción', 'Antofagasta'],
  },
  {
    code: 'CO',
    dialCode: '+57',
    name: 'Colombia',
    flag: '🇨🇴',
    currency: 'COP',
    currencySymbol: 'COP$',
    cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'],
  },
];
